config/routes.rb
Rails.application.routes.draw do
  root to: 'listes#index'
  resources :listes, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :liste
end

app/models/liste.rb
class Liste < ApplicationRecord
  has_many :ingredients, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/controllers/listes_controller.rb
class ListesController < ApplicationController
  def index
    @listes = Liste.all
  end

  def new
    @liste = Liste.new
  end

  def create
    @liste = Liste.new(liste_params)
    if @liste.save
      bind_ingredients_to_liste(params[:liste][:ingredient_ids])
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    Liste.find(params[:id]).destroy
    redirect_to root_path
  end

  private

  def liste_params
    params.require(:liste).permit(:nom, :ingredient_ids)
  end

  def bind_ingredients_to_liste(ingredients_array)
    cleared_array = ingredients_array - ["", nil]
    cleared_array.each do |ingredient|
      nom = Ingredient.find(ingredient)
      test = Ingredient.create!(nom: nom.nom, quantite: "", liste_id: @liste.id)
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BasicCrudForCertif</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/listes/index.html.erb
<h1>Voici les listes de courses</h1>

<div class="container">

  <% @listes.each do |liste| %>
  <div class="liste">
    <p><%= liste.nom %></p>
    <ul>
      <% liste.ingredients.each do |ingredient| %>
      <li><%= ingredient.nom %></li>
      <% end %>
    </ul>
    <%= link_to "Suprimer la recette", liste, method: :delete, data: { confirm: "Etes-vous sûr ?"} %>
  <% end %>
  </div>

  <%= link_to "Créer une nouvelle liste", new_liste_path %>
</div>

app/views/listes/new.html.erb
<div class="container">
  <%= simple_form_for @liste do |f| %>
    <%= f.input :nom %>
    <%= f.association :ingredients, as: :check_boxes %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>